// <auto-generated />
namespace YGN.Store.Management.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddedtrcodetoorderandorderline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddedtrcodetoorderandorderline));
        
        string IMigrationMetadata.Id
        {
            get { return "202404182109267_mig-added-trcode-to-order-and-orderline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
